register_apps!(
    1 => control,
    2 => lfo,
    3 => ad,
    4 => rnd,
    5 => seq8,
    6 => turing,
    7 => clkturing,
    8 => euclid,
    9 => probatrigger,
    10 => notefader,
    11 => offset_att,
    12 => slew,
    13 => follower,
    14 => quantizer,
    15 => midi2cv,
    16 => cv2midi,
    17 => cv2midinote,
    18 => clk_div,
    19 => panner,
    20 => tb3po,
    20 => rnd_plus,
    22 => lfo_plus,
);
